apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello 
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello
  replicas: 2  
  template: 
    metadata: 
      name: hello
      labels:
        app: hello
    spec:
      containers: 
        - name: hello
          image: mylandmarktech/hello:3  
          ports: 
          - containerPort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: green 
spec:
  selector:
    matchLabels:
      app: green
  replicas: 2  
  template: 
    metadata: 
      name: green
      labels:
        app: green
    spec:
      containers: 
        - name: hello
          image: mylandmarktech/hello:4   
          ports: 
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  type: NodePort
  selector:
    app: green
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32100
