apiVersion: v1
kind: Pod
metadata:
  name: teslaapp
  labels:
    app: tesla
spec:
  containers:
  - name: teslap
    image: mdedika1/tesla-app:17
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teslasvc
spec:
  type: ClusterIP
  selector:
    app: tesla
  ports:
  - port: 80
    targetPort: 8080

